title: Composables
items:
  - title: Introduction
    to: /composables
  - title: Cursor Composables
    items:
      - title: useCanvasCursor
        to: /composables/use-canvas-cursor
      - title: useFluidCursor
        to: /composables/use-fluid-cursor
  - title: Popover Composables
    items:
      - title: useMorphingPopover
        to: /composables/use-morphing-popover