title: Components
items:
  - title: Introduction
    to: /components
  - title: 3D Components
    items:
      - title: 3D Card
        to: /components/3d-card
  - title: Background Components
    items:
      - title: Animated Spotlight
        to: /components/animated-spotlight
      - title: Aurora Background
        to: /components/aurora-background
      - title: Background Beams
        to: /components/background-beams
      - title: Background Gradient Animation
        to: /components/background-gradient-animation
      - title: Background Lines
        to: /components/background-lines
      - title: Background Ripple Effect
        to: /components/background-ripple-effect
      - title: Boxes Core
        to: /components/boxes-core
      - title: Directional Light
        to: /components/directional-light
      - title: Dotted Glow Background
        to: /components/dotted-glow-background
      - title: Lamp Container
        to: /components/lamp-container
      - title: Meteors
        to: /components/meteors
      - title: Shooting Stars
        to: /components/shooting-stars
      - title: Stars Background
        to: /components/stars-background
      - title: Vortex
        to: /components/vortex
      - title: AnimatedBackground
        to: /components/animated-background
  - title: Card Components
    items:
      - title: Card Stack
        to: /components/card-stack
      - title: Draggable Card
        to: /components/draggable-card
      - title: Evervault Card
        to: /components/ever-vault-card
      - title: Focus Cards
        to: /components/focus-cards
      - title: Glare Card
        to: /components/glare-card
      - title: Glowing Stars Card
        to: /components/glowing-stars-card
      - title: Wobble Card
        to: /components/wobble-card
  - title: Directional Components
    items:
      - title: Direction Aware Hover
        to: /components/direction-aware-hover
      - title: Direction Aware Hover New
        to: /components/direction-aware-hover-new
  - title: Layout & Background
    items:
      - title: AnimatedGroup
        to: /components/animated-group
      - title: Collision
        to: /components/collision
  - title: Interactive Elements
    items:
      - title: Dock
        to: /components/dock
      - title: Image Comparison
        to: /components/image-comparison
      - title: Morphing Popover
        to: /components/morphing-popover
  - title: Numbers & Text
    items:
      - title: AnimatedNumber
        to: /components/animated-number
      - title: CountingNumber
        to: /components/counting-number
      - title: SlidingNumber
        to: /components/sliding-number
      - title: TextGlitch
        to: /components/text-glitch
      - title: TextGlitch New
        to: /components/text-glitch-new
      - title: TextGradient
        to: /components/text-gradient
      - title: TextLoop
        to: /components/text-loop
      - title: TextMorph
        to: /components/text-morph
      - title: TextReveal
        to: /components/text-reveal
      - title: TextRoll
        to: /components/text-roll
      - title: TextScramble
        to: /components/text-scramble
      - title: TextShimmer
        to: /components/text-shimmer
      - title: TextShimmerWave
        to: /components/text-shimmer-wave
      - title: True Focus
        to: /components/true-focus
      - title: TypingText
        to: /components/typing-text
      - title: Variable Proximity
        to: /components/variable-proximity
      - title: WordRotate
        to: /components/word-rotate
  - title: Visual Effects
    items:
      - title: BorderTrail
        to: /components/border-trail
      - title: Div Grid
        to: /components/div-grid
      - title: Flowing Stroke
        to: /components/flowing-stroke
      - title: GlowEffect
        to: /components/glow-effect
      - title: Glowing Effect
        to: /components/glowing-effect
      - title: Mask Container
        to: /components/mask-container
      - title: Pixelated Canvas
        to: /components/pixelated-canvas
      - title: ProgressiveBlur
        to: /components/progressive-blur
      - title: Spotlight
        to: /components/spotlight
      - title: TracingBeam
        to: /components/tracing-beam
  - title: Interaction & Movement
    items:
      - title: Cursor
        to: /components/cursor
      - title: Drag And Drop
        to: /components/drag-and-drop
      - title: ForceDot
        to: /components/force-dot
      - title: Magnetic
        to: /components/magnetic
      - title: Tilt
        to: /components/tilt
  - title: Scroll & Viewport
    items:
      - title: InView
        to: /components/in-view
      - title: Infinite Slider
        to: /components/infinite-slider
      - title: Scroll Velocity
        to: /components/scroll-velocity
      - title: ScrollProgress
        to: /components/scroll-progress