title: Template
description: Ready to use templates for your next Nuxt UI project
navigation:
  icon: i-lucide-layout
  items:
    - title: Complete Landing Page
      to: /template/landing-page_001
      icon: i-lucide-layout