title: Blocks
description: Collection of reusable UI components and blocks.
navigation:
  icon: i-lucide-layout-grid
  items:
    - title: 'Dashboard Components'
      items:
        - title: 'Analytics Dashboard'
          to: '/blocks/dashboard-components/analytics-dashboard'
        - title: 'User Management Table'
          to: '/blocks/dashboard-components/user-management'
    - title: 'E-commerce'
      items:
        - title: 'Product Grid'
          to: '/blocks/e-commerce/product-grid'
        - title: 'Shopping Cart'
          to: '/blocks/e-commerce/shopping-cart'
    - title: 'Landing Page'
      items:
        - title: 'Feature Showcase'
          to: '/blocks/landing-page/feature-showcase'
        - title: 'Testimonial Carousel'
          to: '/blocks/landing-page/testimonial-carousel'
    - title: 'Blog'
      items:
        - title: 'Blog Listing'
          to: '/blocks/blog/blog-listing'
        - title: 'Article Page'
          to: '/blocks/blog/article-page'
    - title: 'Portfolio'
      items:
        - title: 'Project Gallery'
          to: '/blocks/portfolio/project-gallery'
        - title: 'Case Study'
          to: '/blocks/portfolio/case-study'
    - title: 'Hero Sections'
      items:
        - title: 'Gradient Hero'
          to: '/blocks/hero-sections/gradient-hero'
    - title: 'Navigation'
      items:
        - title: 'Modern Navbar'
          to: '/blocks/navigation/modern-navbar'
    - title: 'Features'
      items:
        - title: 'Feature Grid'
          to: '/blocks/features/feature-grid'
    - title: 'Testimonials'
      items:
        - title: 'Testimonial Carousel'
          to: '/blocks/testimonials/testimonial-carousel'
    - title: 'Pricing'
      items:
        - title: 'Pricing Cards'
          to: '/blocks/pricing/pricing-cards'
    - title: 'Call to Action'
      items:
        - title: 'Centered CTA'
          to: '/blocks/cta/centered-cta'
    - title: 'Footers'
      items:
        - title: 'Multi-column Footer'
          to: '/blocks/footers/multi-column-footer'
    - title: 'Featured Components'
      items:
        - title: 'Animated Spotlight'
          to: '/blocks/featured-components/animated-spotlight'
        - title: 'Animated Gradient'
          to: '/blocks/featured-components/animated-gradient'
        - title: 'Ripple Effect'
          to: '/blocks/featured-components/ripple-effect'