title: Blocks
description: Collection of reusable UI components and blocks.
navigation:
  icon: i-lucide-layout-grid
  items:
    - title: 'Hero Sections'
      items:
        - title: 'Gradient Hero'
          to: '/blocks/hero-sections/gradient-hero'
    - title: 'Navigation'
      items:
        - title: 'Modern Navbar'
          to: '/blocks/navigation/modern-navbar'
    - title: 'Features'
      items:
        - title: 'Feature Grid'
          to: '/blocks/features/feature-grid'
    - title: 'Testimonials'
      items:
        - title: 'Testimonial Carousel'
          to: '/blocks/testimonials/testimonial-carousel'
    - title: 'Pricing'
      items:
        - title: 'Pricing Cards'
          to: '/blocks/pricing/pricing-cards'
    - title: 'Call to Action'
      items:
        - title: 'Centered CTA'
          to: '/blocks/cta/centered-cta'
    - title: 'Footers'
      items:
        - title: 'Multi-column Footer'
          to: '/blocks/footers/multi-column-footer'
    - title: 'Featured Components'
      items:
        - title: 'Animated Spotlight'
          to: '/blocks/featured-components/animated-spotlight'
        - title: 'Animated Gradient'
          to: '/blocks/featured-components/animated-gradient'
        - title: 'Ripple Effect'
          to: '/blocks/featured-components/ripple-effect'